# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: GoInvest

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Select Xcode
      run: sudo xcode-select -switch /Applications/Xcode.app
      
    - name: Build and test
      run: xcodebuild clean build -workspace GoInvest/GoInvest.xcworkspace -scheme "GoInvest" -sdk iphonesimulator -destination "platform=iOS Simulator,name=iPhone 13"
  SwiftLint:
    runs-on: macos-11
    steps:
    - uses: actions/checkout@v1
      
    - name: Lint code using SwiftLint
      run: swiftlint lint --reporter github-actions-logging


